### ISSUE TITLE
visual testing

### ISSUE THREAD

**Issue by Riverzxz** [leijue222/Intra-and-Inter-Human-Relation-Network-for-MPEE#1]
Thanks for your contribution。How to perform visual testing

**Comment by leijue222** [comment]
You can use [vis_demo.py](https://github.com/leijue222/Intra-and-Inter-Human-Relation-Network-for-MPEE/blob/main/vis_demo.py) to do visual testing.
Note that you need to modify the three paths of json_file，imgset_path and out_path. 
https://github.com/leijue222/Intra-and-Inter-Human-Relation-Network-for-MPEE/blob/b4cc80e5dca43e1245341eec819657d39a9914b1/vis_demo.py#L111-L114
json_file will be generated after you run a model test.
