### ISSUE TITLE
lib/core/function.py   code in 42  line

### ISSUE THREAD

**Issue by suijua** [leijue222/Intra-and-Inter-Human-Relation-Network-for-MPEE#10]
![image](https://user-images.githubusercontent.com/98210579/225286890-52716cdb-262e-4543-9605-88036a026e51.png)

 您好！请问 在lib/core/function.py   （42行）处，**input, pos_mas**k等变量  是在哪里定义的？我在**train_loader**未能找到，期待您的回复!

Hello! At lib/core/function. py (line 42),  Where are you  defined **input, pos_mask**? I could not found this in **train_ loader**，expect your reply!

**Comment by leijue222** [comment]
The data will first be processed in [JointsDataset](https://github.com/leijue222/Intra-and-Inter-Human-Relation-Network-for-MPEE/blob/58d02f38ae9903dd820291dee2e3710166bb08cd/lib/dataset/JointsDataset.py#L207), then through [collater](https://github.com/leijue222/Intra-and-Inter-Human-Relation-Network-for-MPEE/blob/58d02f38ae9903dd820291dee2e3710166bb08cd/lib/dataset/collater.py#L14), and finally to [function.py](https://github.com/leijue222/Intra-and-Inter-Human-Relation-Network-for-MPEE/blob/58d02f38ae9903dd820291dee2e3710166bb08cd/lib/core/function.py#L42)

**Comment by suijua** [comment]
![image](https://user-images.githubusercontent.com/98210579/226229111-f4918121-3073-47f2-bd10-7fc7e006ce53.png)
thanks for your reply, what did mean the ' **length**' in line 45

**Comment by leijue222** [comment]
‘**length**’ means the number of people. 
Each image contains a different number of people. We need to count the number of people contained in each image in each round of batch to pave the way for parallel training.
