### ISSUE TITLE
Inferencing queries

### ISSUE THREAD

**Issue by SoumyajitMukherjee-droid** [leijue222/Intra-and-Inter-Human-Relation-Network-for-MPEE#3]
Can the model infer on CPU or only on GPU?
Can it infer high resolution image or at max, what resolution of the image can be inferred?
Can it perform 3D pose estimation?
What is the Inference speed in FPS?

**Comment by leijue222** [comment]
GPU

**Comment by WinstonDeng** [comment]
> Can the model infer on CPU or only on GPU? Can it infer high resolution image or at max, what resolution of the image can be inferred? Can it perform 3D pose estimation? What is the Inference speed in FPS?

1. We infer our model on GPU, but you can run on CPU by setting cuda device.
2. Any resolution image aftering being resized to pre-trained model setting.
3. We have not yet implement it on 3d pose estimation. It could work with our multi-person attentioned design.
4. Around 30fps on A100 cloud server.

**Comment by WinstonDeng** [comment]
> Can the model infer on CPU or only on GPU? Can it infer high resolution image or at max, what resolution of the image can be inferred? Can it perform 3D pose estimation? What is the Inference speed in FPS?

1. We infer our model on GPU, but you can run on CPU by setting cuda device.
2. Any resolution image can be inferred , but need to be resized as pre-trained model input setting.
3. We have not yet implement it on 3d pose estimation. It could work with our multi-person attentioned design.
4. Around 30fps on A100 cloud server.
