### ISSUE TITLE
hrt_base_ochuman_256x192.pth is not a checkpoint file

### ISSUE THREAD

**Issue by xiabc612** [leijue222/Intra-and-Inter-Human-Relation-Network-for-MPEE#4]
OSError: models/base/hrformer/hrt_base_ochuman_256x192.pth is not a checkpoint file
when running:
python tools/train.py --cfg experiments/OCHuman/interformer_ochuman_hrt_192_p3_b8.yaml

**Comment by balazsmorv** [comment]
Nearly identical error:
OSError: models/base/hrformer/hrt_base_coco_384x288.pth is not a checkpoint file
When running: torchrun --nproc_per_node=1 tools/ddp_train.py --cfg experiments/coco/interformer_coco_hrt_288_p2_b4.yaml
Did you manage to solve it?

**Comment by leijue222** [comment]
Please git pull the lateset version, and download the models from [here](https://github.com/leijue222/Intra-and-Inter-Human-Relation-Network-for-MPEE#pretrained-models).
